=== SmBe19/LD35/android/assets/lvl/lvlschema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://games.smeanox.com"
    xmlns="http://games.smeanox.com"
    elementFormDefault="qualified">
    <xs:element name="level">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="description" type="xs:string"/>
                <xs:element name="hero" type="hero"/>
                <xs:element name="platforms" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="platform" maxOccurs="unbounded" type="platform"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="buttons" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="button" maxOccurs="unbounded" type="button"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="actors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actor" maxOccurs="unbounded" type="actor"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="hero">
        <xs:attribute name="start_x" type="xs:float" use="required"/>
        <xs:attribute name="start_y" type="xs:float" use="required"/>
        <xs:attribute name="start_form" type="hero_form" use="optional" default="human"/>
    </xs:complexType>

    <xs:simpleType name="hero_form">
        <xs:restriction base="xs:string">
            <xs:enumeration value="human"/>
            <xs:enumeration value="turtle"/>
            <xs:enumeration value="wolf"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="platform">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
        <xs:attribute name="width" type="xs:float" use="required"/>
        <xs:attribute name="height" type="xs:float" use="required"/>
        <xs:attribute name="start_x" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="start_y" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="end_x" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="end_y" type="xs:float" use="optional" default="0"/>
        <xs:attribute name="moving_enabled" type="xs:boolean" use="optional" default="true"/>
        <xs:attribute name="moving_velo" type="xs:float" use="optional" default="1"/>
        <xs:attribute name="hold_time" type="xs:float" use="optional" default="1"/>
    </xs:complexType>

    <xs:complexType name="button">
        <xs:sequence>
            <xs:element name="toggle_interact" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="dest_id" type="xs:int" use="required"/>
                </xs:complexType>
            </xs:element>
            <xs:element name="toggle_active" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:attribute name="dest_id" type="xs:int" use="required"/>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
        <xs:attribute name="width" type="xs:float" use="required"/>
        <xs:attribute name="height" type="xs:float" use="required"/>
    </xs:complexType>

    <xs:complexType name="actor">
        <xs:attribute name="id" type="xs:int" use="required"/>
        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" use="required"/>
        <xs:attribute name="width" type="xs:float" use="required"/>
        <xs:attribute name="height" type="xs:float" use="required"/>
    </xs:complexType>
</xs:schema>

=== SmBe19/LD35/android/assets/lvl/lvl3.xml
<?xml version="1.0"?>
<level xmlns="http://games.smeanox.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://games.smeanox.com lvlschema.xsd">
    <description>Level 3</description>
    <camera min_x="-6" max_x="9" start_x="0" />
    <hero start_x="-23" start_y="-11" dest_x="28.5" dest_y="8.5"/>
    <platforms>
        <platform id="98" x="-27.3" y="0" width="2" height="30"/>
        <platform id="99" x="30.3" y="0" width="2" height="30"/>

        <platform id="1" x="-23" y="-13" width="8" height="2"/>
        <platform id="2" x="-15" y="-9" width="8" height="10"/>
        <platform id="3" x="-17" y="-2" width="4" height="4"/>
        <platform id="4" x="-14" y="2" width="10" height="6"/>
        <platform id="5" x="5" y="-12" width="32" height="4"/>
        <platform id="6" x="25" y="-3" width="8" height="22"/>
        <platform id="7" x="18" y="0" width="6" height="2"/>
        <platform id="8" x="17" y="7" width="8" height="2"/>
        <platform id="9" x="10" y="7.5" width="4" height="1" moving_enabled="false" start_x="10" start_y="7.5" end_x="10" end_y="2.5" hold_time="0.2" moving_velo="3" type="oldschool"/>
        <platform id="10" x="-9" y="-9.5" width="4" height="1" moving_enabled="false" start_x="-9" start_y="-9.5" end_x="-9" end_y="-4.5" hold_time="0.2" moving_velo="3" type="oldschool"/>
        <platform id="11" x="8" y="1.5" width="6" height="1" type="oldschool"/>
    </platforms>
    <ladders>
        <ladder id="1" x="-19.5" width="1" start_y="-12" end_y="5"/>
        <ladder id="2" x="18.5" width="1" start_y="-10" end_y="1"/>
        <ladder id="3" x="13.5" width="1" start_y="0" end_y="5" in_air="true"/>
    </ladders>
    <buttons>
        <button id="1" x="-14.5" y="-3.5" width="1" height="1">
            <toggle_interact dest_id="9" />
        </button>
        <button id="1" x="6.5" y="2.5" width="1" height="1">
            <toggle_interact dest_id="10" />
        </button>
    </buttons>
    <actors>
        <actor id="1" x="28.5" y="8.5" width="1" height="1" texture="signright" collision="false" dynamic="false"/>
    </actors>
</level>

=== SmBe19/LD35/android/assets/lvl/lvl8.xml
<?xml version="1.0"?>
<level xmlns="http://games.smeanox.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://games.smeanox.com lvlschema.xsd">
    <description>Level 5</description>
    <camera min_x="-6" max_x="11" start_x="0" />
    <hero start_x="-23" start_y="-11" dest_x="4.75" dest_y="13.25"/>
    <!--<hero start_x="14.75" start_y="-10" dest_x="28.5" dest_y="8.5"/>-->
    <platforms>
        <platform id="98" x="-27.3" y="0" width="2" height="30"/>
        <platform id="99" x="32.3" y="0" width="2" height="30"/>
        <platform id="100" x="2" y="-15.4" width="70" height="1" type="oldschool"/>

        <platform id="1" x="-16.25" y="-15" width="20.5" height="2.5"/>
        <platform id="2" x="-14.25" y="-10" width="10.5" height="0.5"/>

        <platform id="3" x="-18.25" y="-13" width="2.5" height="0.5" moving_enabled="true" start_y= "-10" end_y="-14" hold_time="0.001" moving_velo="6.2"/>
        <platform id="4" x="-15.75" y="-12" width="2.5" height="0.5" moving_enabled="true" start_y= "-10" end_y="-14" hold_time="0.001" moving_velo="6.2"/>
        <platform id="5" x="-13.25" y="-11" width="2.5" height="0.5" moving_enabled="true" start_y= "-10" end_y="-14" hold_time="0.001" moving_velo="6.2"/>
        <platform id="6" x="-10.75" y="-10" width="2.5" height="0.5" moving_enabled="true" start_y= "-10" end_y="-14" hold_time="0.001" moving_velo="6.2"/>

        <platform id="7" x="-3" y="-13" width="1" height="0.5" type="destr"/>
        <platform id="8" x="5" y="-12" width="1" height="0.5" type="destr"/>

        <platform id="9" x="11.25" y="-14" width="2.5" height="4.5"/>
        <platform id="10" x="14.75" y="-64" width="4.5" height="104.5" moving_enabled="false" end_y="-44.75" hold_time="10"/>
        <platform id="11" x="14.75" y="-12.9" width="4.5" height="4.5" moving_enabled="false" end_y="-30" moving_velo="10" hold_time="10000"/>
        <platform id="12" x="18.25" y="-14" width="2.5" height="4.5"/>

        <platform id="13" x="10.75" y="-9" width="2.5" height="0.5" moving_enabled="false" start_x="7.25" start_y="-6" end_x ="10.75" end_y="-9" hold_time="0.3" moving_velo="2"/>
        <!--<platform id="14" x="9" y="-5" width="2.5" height="0.5" moving_enabled="false" start_x="7.25" start_y="-3.5" end_x ="10.75" end_y="-6.5" hold_time="0.3" moving_velo="2"/>-->
        <platform id="15" x="7.25" y="-1" width="2.5" height="0.5" moving_enabled="false" start_x="7.25" start_y="-1" end_x ="10.75" end_y="-4" hold_time="0.3" moving_velo="2"/>

        <platform id="16" x="0.25" y="2" width="4.5" height="0.5"/>

        <platform id="50" x="3.25" y="11.25" width="4.5" height="2.5"/>
        <platform id="51" x="3.25" y="8.75" width="8.5" height="2.5"/>
    </platforms>
    <buttons>
        <button id="1" x="-0.5" y="2.75" width="1" height="1">
            <toggle_interact dest_id="11" />
        </button>
        <button id="2" x="24.5" y="-14.5" width="1" height="1">
            <toggle_interact dest_id="13" />
            <toggle_interact dest_id="15" />
        </button>
        <button id="3" x="14.75" y="-11.25" width="1" height="1">
            <toggle_interact dest_id="10" />
            <toggle_interact dest_id="13" />
            <toggle_interact dest_id="15" />
        </button>
    </buttons>
    <waters>
        <water id="1" x="2" y="-15.1" width="16" height="2"/>
    </waters>
    <actors>
        <actor id="1" x="3.25" y="13.5" width="2" height="2" texture="sign" collision="true" dynamic="false"/>
    </actors>
</level>

=== SmBe19/LD35/android/assets/lvl/lvl5.xml
<?xml version="1.0"?>
<level xmlns="http://games.smeanox.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://games.smeanox.com lvlschema.xsd">
    <description>Level 5</description>
    <camera min_x="-6" max_x="11" start_x="0" />
    <hero start_x="-23" start_y="-11" dest_x="28.5" dest_y="8.5"/>
    <!--<hero start_x="28.5" start_y="-9" dest_x="28.5" dest_y="8.5"/>-->
    <platforms>
        <platform id="98" x="-27.3" y="0" width="2" height="30"/>
        <platform id="99" x="32.3" y="0" width="2" height="30"/>
        <platform id="100" x="2" y="-15.4" width="50" height="1" type="oldschool"/>

        <platform id="1" x="-23" y="-14" width="8" height="4"/>
        <platform id="2" x="-12" y="-10" width="4" height="1" type="oldschool"/>
        <platform id="3" x="-2" y="-10" width="4" height="1" type="oldschool"/>
        <platform id="4" x="8" y="-9" width="4" height="1" type="oldschool"/>
        <platform id="5" x="18" y="-11" width="4" height="1" type="oldschool"/>
        <platform id="6" x="30" y="-13" width="8" height="6"/>
        <!--<platform id="7" x="31.3" y="-4" width="2" height="22"/>-->

        <platform id="14" x="22.75" y="4.75" width="0.5" height="3"/>
        <platform id="8" x="25.7" y="2.9" width="6" height="2"/>
        <platform id="16" x="-6" y="-1" width="0.5" height="2.5 "/>

        <platform id="10" x="-12" y="-2" width="4" height="1" type="oldschool" moving_enabled="false" end_x="-2" end_y="-2" hold_time="0.2" moving_velo="3"/>
        <platform id="11" x="8" y="-2" width="4" height="1" type="oldschool"/>
        <platform id="12" x="13" y="-3" width="4" height="1" type="oldschool" moving_enabled="false" end_x="18" end_y="-3" hold_time="0.2" moving_velo="3"/>
        <platform id="13" x="26" y="-2" width="4" height="1" type="oldschool"/>

        <platform id="15" x="26" y="7" width="8" height="2"/>
        <platform id="17" x="-23" y="4.75" width="6.5" height="0.5"/>
        <!--3 * t = 8
        v * 8/3 = sqrt(6^2+2^2)
        => v = 2.371708245-->
        <platform id="18" x="-2" y="6" width="4" height="1" type="oldschool" moving_enabled="false" end_x="-10" end_y="6" hold_time="0.2" moving_velo="3"/>
        <platform id="19" x="10" y="5" width="4" height="1" type="oldschool" moving_enabled="false" end_x="16" end_y="7" hold_time="0.2" moving_velo="2.37108245"/>

    </platforms>
    <ladders>
        <ladder id="1" x="-20.5" width="1" start_y="-3" end_y="5" in_air="true"/>
        <ladder id="2" x="29.5" width="1" start_y="-10" end_y="4"/>
    </ladders>
    <buttons>
        <button id="1" x="-24.5" y="5.5" width="1" height="1">
            <toggle_interact dest_id="18" />
            <toggle_interact dest_id="19" />
        </button>
        <button id="2" x="24.5" y="4.5" width="1" height="1">
            <toggle_interact dest_id="10" />
            <toggle_interact dest_id="12" />
        </button>
    </buttons>
    <waters>
        <water id="1" x="3.5" y="-14.1" width="45" height="4"/>
    </waters>
    <actors>
        <actor id="1" x="28.5" y="8.5" width="1" height="1" texture="signright" collision="false" dynamic="false"/>
    </actors>
</level>
